### ISSUE TITLE
jsoncpp version is too old

### ISSUE THREAD

**Issue by webispy** [nugu-developers/nugu-linux#120]
Linux NUGU-SDK is currently using version 0.10.x of jsoncpp, which is no longer maintained by the community.

Therefore, it is necessary to upgrade to the latest version for security patch or bug patch.

FYI, the latest version of jsoncpp is 1.9.3
https://github.com/open-source-parsers/jsoncpp

And, please refer to the following benchmark graph. **RapidJson looks much better.**
https://github.com/miloyip/nativejson-benchmark

**Comment by JeanTracker** [comment]
We will consider RapidJson review and application.

**Comment by webispy** [comment]
Resolved by #906
